// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/faber-numeris/beholder/authn/internal/core/domain"
	"github.com/faber-numeris/beholder/authn/internal/ports/outbound"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ConfirmUserRegistration provides a mock function with given fields: ctx, userID
func (_m *MockRepository) ConfirmUserRegistration(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUserRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ConfirmUserRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUserRegistration'
type MockRepository_ConfirmUserRegistration_Call struct {
	*mock.Call
}

// ConfirmUserRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) ConfirmUserRegistration(ctx interface{}, userID interface{}) *MockRepository_ConfirmUserRegistration_Call {
	return &MockRepository_ConfirmUserRegistration_Call{Call: _e.mock.On("ConfirmUserRegistration", ctx, userID)}
}

func (_c *MockRepository_ConfirmUserRegistration_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_ConfirmUserRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_ConfirmUserRegistration_Call) Return(_a0 error) *MockRepository_ConfirmUserRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ConfirmUserRegistration_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_ConfirmUserRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user, passwordHash
func (_m *MockRepository) CreateUser(ctx context.Context, user *domain.User, passwordHash []byte) (*domain.User, error) {
	ret := _m.Called(ctx, user, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, []byte) (*domain.User, error)); ok {
		return rf(ctx, user, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, []byte) *domain.User); ok {
		r0 = rf(ctx, user, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, []byte) error); ok {
		r1 = rf(ctx, user, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - passwordHash []byte
func (_e *MockRepository_Expecter) CreateUser(ctx interface{}, user interface{}, passwordHash interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user, passwordHash)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(ctx context.Context, user *domain.User, passwordHash []byte)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User), args[2].([]byte))
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(_a0 *domain.User, _a1 error) *MockRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *domain.User, []byte) (*domain.User, error)) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserConfirmation provides a mock function with given fields: ctx, userID, token, expiresAt
func (_m *MockRepository) CreateUserConfirmation(ctx context.Context, userID string, token string, expiresAt time.Time) (*domain.UserConfirmation, error) {
	ret := _m.Called(ctx, userID, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserConfirmation")
	}

	var r0 *domain.UserConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserConfirmation, error)); ok {
		return rf(ctx, userID, token, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserConfirmation); ok {
		r0 = rf(ctx, userID, token, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConfirmation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, userID, token, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateUserConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserConfirmation'
type MockRepository_CreateUserConfirmation_Call struct {
	*mock.Call
}

// CreateUserConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - token string
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) CreateUserConfirmation(ctx interface{}, userID interface{}, token interface{}, expiresAt interface{}) *MockRepository_CreateUserConfirmation_Call {
	return &MockRepository_CreateUserConfirmation_Call{Call: _e.mock.On("CreateUserConfirmation", ctx, userID, token, expiresAt)}
}

func (_c *MockRepository_CreateUserConfirmation_Call) Run(run func(ctx context.Context, userID string, token string, expiresAt time.Time)) *MockRepository_CreateUserConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CreateUserConfirmation_Call) Return(_a0 *domain.UserConfirmation, _a1 error) *MockRepository_CreateUserConfirmation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateUserConfirmation_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (*domain.UserConfirmation, error)) *MockRepository_CreateUserConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteUser(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockRepository_DeleteUser_Call {
	return &MockRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockRepository_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteUser_Call) Return(_a0 error) *MockRepository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserConfirmation provides a mock function with given fields: ctx, userID
func (_m *MockRepository) DeleteUserConfirmation(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteUserConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserConfirmation'
type MockRepository_DeleteUserConfirmation_Call struct {
	*mock.Call
}

// DeleteUserConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) DeleteUserConfirmation(ctx interface{}, userID interface{}) *MockRepository_DeleteUserConfirmation_Call {
	return &MockRepository_DeleteUserConfirmation_Call{Call: _e.mock.On("DeleteUserConfirmation", ctx, userID)}
}

func (_c *MockRepository_DeleteUserConfirmation_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_DeleteUserConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteUserConfirmation_Call) Return(_a0 error) *MockRepository_DeleteUserConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteUserConfirmation_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteUserConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockRepository_GetUserByEmail_Call {
	return &MockRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetUserByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(_a0 *domain.User, _a1 error) *MockRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserConfirmationByToken provides a mock function with given fields: ctx, token
func (_m *MockRepository) GetUserConfirmationByToken(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserConfirmationByToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserConfirmationByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserConfirmationByToken'
type MockRepository_GetUserConfirmationByToken_Call struct {
	*mock.Call
}

// GetUserConfirmationByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRepository_Expecter) GetUserConfirmationByToken(ctx interface{}, token interface{}) *MockRepository_GetUserConfirmationByToken_Call {
	return &MockRepository_GetUserConfirmationByToken_Call{Call: _e.mock.On("GetUserConfirmationByToken", ctx, token)}
}

func (_c *MockRepository_GetUserConfirmationByToken_Call) Run(run func(ctx context.Context, token string)) *MockRepository_GetUserConfirmationByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserConfirmationByToken_Call) Return(_a0 string, _a1 error) *MockRepository_GetUserConfirmationByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserConfirmationByToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRepository_GetUserConfirmationByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCredentials provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserCredentials(ctx context.Context, email string) (*domain.UserCredentials, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCredentials")
	}

	var r0 *domain.UserCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserCredentials, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserCredentials); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCredentials'
type MockRepository_GetUserCredentials_Call struct {
	*mock.Call
}

// GetUserCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserCredentials(ctx interface{}, email interface{}) *MockRepository_GetUserCredentials_Call {
	return &MockRepository_GetUserCredentials_Call{Call: _e.mock.On("GetUserCredentials", ctx, email)}
}

func (_c *MockRepository_GetUserCredentials_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserCredentials_Call) Return(_a0 *domain.UserCredentials, _a1 error) *MockRepository_GetUserCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserCredentials_Call) RunAndReturn(run func(context.Context, string) (*domain.UserCredentials, error)) *MockRepository_GetUserCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, params
func (_m *MockRepository) ListUsers(ctx context.Context, params *outboundport.ListUsersParams) ([]*domain.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *outboundport.ListUsersParams) ([]*domain.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *outboundport.ListUsersParams) []*domain.User); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *outboundport.ListUsersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - params *outboundport.ListUsersParams
func (_e *MockRepository_Expecter) ListUsers(ctx interface{}, params interface{}) *MockRepository_ListUsers_Call {
	return &MockRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, params)}
}

func (_c *MockRepository_ListUsers_Call) Run(run func(ctx context.Context, params *outboundport.ListUsersParams)) *MockRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*outboundport.ListUsersParams))
	})
	return _c
}

func (_c *MockRepository_ListUsers_Call) Return(_a0 []*domain.User, _a1 error) *MockRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListUsers_Call) RunAndReturn(run func(context.Context, *outboundport.ListUsersParams) ([]*domain.User, error)) *MockRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockRepository) Ping() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Ping() *MockRepository_Ping_Call {
	return &MockRepository_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockRepository_Ping_Call) Run(run func()) *MockRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Ping_Call) Return(_a0 bool) *MockRepository_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Ping_Call) RunAndReturn(run func() bool) *MockRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *MockRepository) UpdatePassword(ctx context.Context, userID string, passwordHash []byte) error {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - passwordHash []byte
func (_e *MockRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwordHash interface{}) *MockRepository_UpdatePassword_Call {
	return &MockRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwordHash)}
}

func (_c *MockRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID string, passwordHash []byte)) *MockRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockRepository_UpdatePassword_Call) Return(_a0 error) *MockRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *MockRepository) UpdateUser(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockRepository_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockRepository_UpdateUser_Call {
	return &MockRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockRepository_UpdateUser_Call) Run(run func(ctx context.Context, user *domain.User)) *MockRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockRepository_UpdateUser_Call) Return(_a0 error) *MockRepository_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateUser_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
