// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHashingService is an autogenerated mock type for the HashingService type
type MockHashingService struct {
	mock.Mock
}

type MockHashingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashingService) EXPECT() *MockHashingService_Expecter {
	return &MockHashingService_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: ctx, password
func (_m *MockHashingService) HashPassword(ctx context.Context, password []byte) (string, error) {
	ret := _m.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return rf(ctx, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashingService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockHashingService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - password []byte
func (_e *MockHashingService_Expecter) HashPassword(ctx interface{}, password interface{}) *MockHashingService_HashPassword_Call {
	return &MockHashingService_HashPassword_Call{Call: _e.mock.On("HashPassword", ctx, password)}
}

func (_c *MockHashingService_HashPassword_Call) Run(run func(ctx context.Context, password []byte)) *MockHashingService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockHashingService_HashPassword_Call) Return(_a0 string, _a1 error) *MockHashingService_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashingService_HashPassword_Call) RunAndReturn(run func(context.Context, []byte) (string, error)) *MockHashingService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: ctx, password, hash
func (_m *MockHashingService) VerifyPassword(ctx context.Context, password []byte, hash string) (bool, error) {
	ret := _m.Called(ctx, password, hash)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) (bool, error)); ok {
		return rf(ctx, password, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) bool); ok {
		r0 = rf(ctx, password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = rf(ctx, password, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashingService_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockHashingService_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - password []byte
//   - hash string
func (_e *MockHashingService_Expecter) VerifyPassword(ctx interface{}, password interface{}, hash interface{}) *MockHashingService_VerifyPassword_Call {
	return &MockHashingService_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, password, hash)}
}

func (_c *MockHashingService_VerifyPassword_Call) Run(run func(ctx context.Context, password []byte, hash string)) *MockHashingService_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string))
	})
	return _c
}

func (_c *MockHashingService_VerifyPassword_Call) Return(_a0 bool, _a1 error) *MockHashingService_VerifyPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashingService_VerifyPassword_Call) RunAndReturn(run func(context.Context, []byte, string) (bool, error)) *MockHashingService_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockHashingService) Ping() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockHashingService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockHashingService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockHashingService_Expecter) Ping() *MockHashingService_Ping_Call {
	return &MockHashingService_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockHashingService_Ping_Call) Run(run func()) *MockHashingService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHashingService_Ping_Call) Return(_a0 bool) *MockHashingService_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHashingService_Ping_Call) RunAndReturn(run func() bool) *MockHashingService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHashingService creates a new instance of MockHashingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashingService {
	mock := &MockHashingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
